### ISSUE TITLE
provide a CHANGELOG

### ISSUE THREAD

**Issue by jfirebaugh** [substack/module-deps#100]
I'm trying to debug a problem that appears to cropped up when module-deps was upgraded from 3.7.3 to 3.9.1. It would help me narrow down on the issue faster if there was a CHANGELOG or HISTORY.md, as is common for many projects. Would you please consider this?

**Comment by zertosh** [comment]
Agreed, but it comes down a bandwidth problem – we're all doing this on our free time. All I can offer now is that the commit messages are usually pretty good, and github gives you an easy way to compare across revs (https://github.com/substack/module-deps/compare/3.7.3...v3.9.1).
