### ISSUE TITLE
Provide untransformed source in output

### ISSUE THREAD

**Issue by tmcw** [substack/module-deps#101]
I'm using module-deps in documentationjs and just started to use babelify as a transform [to support JSX](https://github.com/documentationjs/documentation/issues/135). I want to crawl dependencies of ES6 code, but I _don't_ want to transform that code in the output - otherwise the inline code examples of modules will be different than the actual code in the repository.

Is it possible that module-deps could return the untransformed source in addition the the transformed source in the output stream?

**Comment by zertosh** [comment]
As far a dedicated API for this, I don't think the additional complexity is worth it. However, there are a few ways you can go about it, the easiest one is to just grab the original source from the source maps:

```js
var babelify = require('babelify');
var convert = require('convert-source-map');
var mdeps = require('module-deps');

var md = mdeps();
md.write({transform: babelify})
md.end(__dirname + '/src/index.js');

md.on('data', function(row) {
  var transformedSource = row.source;
  var sourceMap = convert.fromSource(row.source).toObject();
  var originalSource = sourceMap.sourcesContent[0];
  // remove the sourcemaps if you didn't want them in the first place:
  // row.source = convert.removeComments(row.source);
});
```

**Comment by tmcw** [comment]
:+1: thanks, that fixes the issue for me.
