### ISSUE TITLE
If `row.file` and `row.expose` are equal, transforms are not applied

### ISSUE THREAD

**Issue by Joris-van-der-Wel** [substack/module-deps#105]
If `row.file` and `row.expose` are equal, transforms are not applied. Unless it is a global transform.

```javascript
'use strict';
const Deps = require('module-deps');
const through = require('through2');

const deps = new Deps({
  transform: [
    [
      function(file) {
        console.log('transform:', file);
        return through();
      }
    ]
  ]
});

let file = './foo.js';
deps.end({ file: file, expose: file });
```

In this example, the log line is never reached. 

This is because the value of `expose` is regarded as a builtin. See: line [319](https://github.com/substack/module-deps/blob/4bb70b69e6766808258409274af466e4a94b38e9/index.js#L319) and [369](https://github.com/substack/module-deps/blob/4bb70b69e6766808258409274af466e4a94b38e9/index.js#L369)

**Comment by jmm** [comment]
Related: https://github.com/substack/module-deps/pull/65#issuecomment-70507321.

**Comment by Joris-van-der-Wel** [comment]
Ah there it is, I had been searching for the original PR. I opened a PR with a short fix and some tests: #106

This issue breaks karma-browserify (if you update its browserify dependency to version 12 instead of 10).

**Comment by jmm** [comment]
@Joris-van-der-Wel I would've fixed this a long time ago except I was looking for feedback on my comment (like what the intent of the existing code was), so I think others will need to chime in here / on the PR. Thank you, BTW, for contributing!

**Comment by Joris-van-der-Wel** [comment]
> Thank you, BTW, for contributing

Sure!, this is my third PR ;)

Anyway, if this behaviour was intentional, should it not have been tested for?

I suspect this behaviour was introduced in https://github.com/substack/module-deps/commit/3af85df6494a8afd0b02ded88b66d3080c734146 by @substack. Indeed, karma-browserify currently ends up with module-deps 3.9.1, which is tagged before that commit. Which is why I am unable to upgrade browserify for karma-browserify (regression).

**Comment by jmm** [comment]
@Joris-van-der-Wel 
> Sure!, this is my third PR ;)

In that case, I'ma thank you 3 more times before you leave: one, two, three. Seriously though, that is awesome, thank you for that :)

> Anyway, if this behaviour was intentional, should it not have been tested for?

I'm not suggesting it was intentional -- I don't know. It apparently wasn't tested for or against. There's a lot of stuff that's not tested as well as it could be. I'll have to take a look at what you changed sometime and see if it helps me understand what I was wondering about before.
