### ISSUE TITLE
Cannot set detective opts from module-deps and browserify

### ISSUE THREAD

**Issue by kzc** [substack/module-deps#108]
Would it be possible to expose detective `opts` from module-deps and ultimately browserify?

https://github.com/substack/module-deps/blob/f3114e180737b5456971fa144b0a62c3c27abf40/index.js#L442

```
try { var deps = detective(src) }
```

Notice that second argument not supplied to detective() for `opts`.

I'd like to override detective's opts.isRequire function from browserify (via module-deps' opts). Or is there another way to achieve this without patching module-deps and/or detective code?

**Comment by tellnes** [comment]
That should be trivial to implement. I suggest you opens a pull request.
