### ISSUE TITLE
Process hangs when pass module-deps options to transforms

### ISSUE THREAD

**Issue by astalker** [substack/module-deps#117]
This is a dependency of browserify and is causing our installs to fail.

This commit doesn't check for undefined.
https://github.com/substack/module-deps/commit/b22b584b47c18de3cc3e054f5f20177ca138acd0

```
TypeError: Cannot call method 'hasOwnProperty' of undefined
```

I don't really have much more context on this mainly due to it being a depedency from browserify but I can see in debugging that some in cases `trOpts` is an empty object, has a key or is also undefined.

I can try to provide more details if required but I guess a simple check for undefined would make sense (although I'm not certain on the purpose of the change which is why I've not made a PR).

**Comment by yoshuawuyts** [comment]
Would this solve the issue on [L254](https://github.com/substack/module-deps/blob/b22b584b47c18de3cc3e054f5f20177ca138acd0/index.js#L254) ?
```js
trOpts._flags = (trOpts && trOpts.hasOwnProperty('_flags')) ? trOpts._flags : self.options;
```

**Comment by nicolas-pantel** [comment]
No, I have following error:

TypeError: Cannot set property '_flags' of undefined

**Comment by bendrucker** [comment]
I don't see how options can ever end up defined coming from browserify:

https://github.com/substack/node-browserify/blob/071642ad9cbb44cb530d43edfac17c5077a9442c/index.js#L312

**Comment by ziflex** [comment]
Same here

**Comment by stefanoverna** [comment]
@bendrucker the problem is due to the fact that `tr` is an array (`[ 'babelify']` in my case)

https://github.com/substack/module-deps/blob/b22b584b47c18de3cc3e054f5f20177ca138acd0/index.js#L250-L253

**Comment by jmm** [comment]
What's the minimal repro for this?

**Comment by bendrucker** [comment]
@jmm See https://github.com/substack/module-deps/pull/119. This would happen for array transforms without options:

```json
{
  "browserify": {
    "transform": [
      ["my-transform"]
    ]
  }
}
```
