### ISSUE TITLE
Module-deps@4.1.1  asyncWrite is not a function

### ISSUE THREAD

**Issue by Apindes** [substack/module-deps#165]
**In file _stream_writable.js  process-nextick-args module imported.**
`var processNextTick = require('process-nextick-args');`
processNextTick - is an object **not a function**.

So this line of code 
`var asyncWrite = !process.browser && ['v0.10', 'v0.9.'].indexOf(process.version.slice(0, 5)) > -1 ? setImmediate : processNextTick`
should be 
`var asyncWrite = !process.browser && ['v0.10', 'v0.9.'].indexOf(process.version.slice(0, 5)) > -1 ? setImmediate : processNextTick.nextTick`
Since we try to call asyncWrite **as a method** but get Object instance.

**Comment by goto-bus-stop** [comment]
That code is not in module-deps, so I'm not sure what we can do about it.

Note that 4.1.1 is quite old so you should probably upgrade if possible!

**Comment by Apindes** [comment]
Your` re right)  It was bug in readable-stream package. Sorry for a miss.
