### ISSUE TITLE
error when encountering core packages?

### ISSUE THREAD

**Issue by DTrejo** [substack/module-deps#23]
I try to run module-deps on this file:

```
require('assert')
```

and I get this error message

```
§ module-deps test.js
[
{"id":"test.js","source":"require('assert')\n","deps":{"assert":"assert"},"entry":true}
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: ENOENT, open 'assert' while resolving "assert" from file /Users/dtrejo/Dropbox/dev/lazytemplating/test.js
    at /usr/local/lib/node_modules/module-deps/index.js:112:29
    at fs.js:207:20
    at Object.oncomplete (fs.js:107:15)
```

It seems that core modules are not correctly processed?
D

**Comment by olsonpm** [comment]
@DTrejo - Mind explaining how you did this?  I'm trying to use module-deps to display a nicer looking dependency tree, but it breaks upon trying to parse the 'path' module, and I'm having trouble figuring out why.

**Comment by DTrejo** [comment]
Hi olson, I ended up using required in my project: https://github.com/DTrejo/run.js/blob/2.0/run

Hopefully this helps. I don't think I'm using module-deps directly

**Comment by olsonpm** [comment]
Ah - that's what I should have done.  I was so stuck on trying to find a CLI library that did what I wanted, that I bypassed 'required'.

For the sake of future readers, I ended up forking module-deps and using the 'core_modules_list' found in [async-resolve](https://github.com/Meettya/async-resolve/blob/master/src/resolver.coffee#L22) to filter core dependencies from being read.
