### ISSUE TITLE
no way to dynamically handle missing modules

### ISSUE THREAD

**Issue by clux** [substack/module-deps#24]
Hi!

I am trying to find module deps from an entry point, but ignore missing requires. These typically come about because people conditionally include coverage stuff that's in devDependencies. So the `filter` option would not work.

At the moment, if one file fails to resolve, the best option I've found is to catch it by binding a handler to the 'error' event on the stream, but if this occurs the 'end' event never fires.

Is this a stream issue, or is there's a way to do this?

**Comment by zertosh** [comment]
I know this is an ancient question, but there's an `ignoreMissing` option now. Sorry :disappointed:

**Comment by clux** [comment]
Ooh, thank you! That probably allows me to fix an ancient issue I had ignored for a while :)
