### ISSUE TITLE
windows files are all topLevel

### ISSUE THREAD

**Issue by Cactusbone** [substack/module-deps#35]
var isTopLevel = mains.some(function (main) {
            var m = path.relative(path.dirname(main), file);
            return m.split('/').indexOf('node_modules') < 0;
        });

This code fails in windows (8.1 in my case) since m contains backslashes (\\) and not slashes (/) so dependencies are indeed as topLevel and transforms are applied.

maybe use path.sep as separator ?
http://nodejs.org/docs/latest/api/path.html#path_path_sep

**Comment by zertosh** [comment]
Fixed in https://github.com/substack/module-deps/pull/75
