### ISSUE TITLE
Missing check for cb causes fatal error

### ISSUE THREAD

**Issue by jnicholl** [substack/module-deps#53]
At https://github.com/substack/module-deps/blob/master/index.js#L258 the cb is not checked for validity. All other occurrences (as of today) in the function are checked except this one.

**Comment by jardilio** [comment]
I'm having the same issue at https://github.com/substack/module-deps/blob/master/index.js#L315, there is no null/undefined check on cb in the walk function at this line and the function is called from several locations internally in this file with no callback. This is causing a "fatal error: undefined is not a function" exception to be thrown for me with browserify when trying to use externals. Other places in the same function body are doing null/undefined checks on cb before execution.
