### ISSUE TITLE
Configurable depth?

### ISSUE THREAD

**Issue by tmcw** [substack/module-deps#62]
Is it possible to configure how deep module-deps looks, or grab the depth when it iterates to ignore dependencies beyond a certain level?

**Comment by zertosh** [comment]
Afraid not. Though https://github.com/substack/module-deps/pull/63 would open up the possibility for you to define a custom "detective" - which could be used for this. But I don't see the feature being developed. Is this something you need?

**Comment by tmcw** [comment]
Never mind - the use case I had was better solved by an ignore than by depth.
