### ISSUE TITLE
__dirname points to wrong package causing 'package' event to be omitted

### ISSUE THREAD

**Issue by lukas-zech-software** [substack/module-deps#73]
I'm using browserify 9.0.3 using module-deps 3.7.2 and my code listens on the bundle.on('package') event.
I noticed that the event is sometimes not triggered for some packages, although the package gets included properly.
It does not occur reliable even if the same code is executed twice, so it seems to be some sort of async race condition.

Example:
```javascript
require('package1');
require('package2');
require('package3');
```
These events are fired:
```javascript
bundle.on('package',function(){ //package1 });
bundle.on('package',function(){ //package3 });
```
I tracked the problem down to [this line](https://github.com/substack/module-deps/blob/master/index.js#L308) where the ___self._emittedPkg___ object already contains 'package2', although the 'package' even was not yet emitted for this package.

Digging further I found that in the [resolver function](https://github.com/substack/module-deps/blob/master/index.js#L158) the following situation may occur:

```javascript
// pkgdir holds the directory to 'package1'
// pkg.name holds the name of 'package2'
if (pkg && pkgdir) pkg.__dirname = pkgdir;
```

So it seems that the __packageFilter__ function is called by another callback before the __resolver__ function executes for this package? Just guessing though, I was not able to track it down further.

It seems to be similar to #67 and maybe also connected to (https://github.com/substack/node-resolve/issues/69)
But it differs to both issues in the fact, that __dirname does not simply point to a wrong path in the package but to a complete wrong package.

**Comment by pmowrer** [comment]
+1 Just debugged a similar scenario and came to the same conclusion
