### ISSUE TITLE
"Arguments to path.resolve must be strings" Error on v3.7.4

### ISSUE THREAD

**Issue by superbrothers** [substack/module-deps#77]
```
path.js:422
      throw new TypeError('Arguments to path.resolve must be strings');
```

`path.resolve` throw error when `row.basedir` is undefined.
```javascript
if (row.entry !== false) self.entries.push(path.resolve(row.basedir, row.file));
```
https://github.com/substack/module-deps/compare/3.7.3...3.7.4#diff-168726dbe96b3ce427e7fedce31bb0bcR84

**Comment by youknowriad** [comment]
+1

**Comment by superbrothers** [comment]
I'm using browserify@9.0.4
https://gist.github.com/superbrothers/7f5fc1a678a00dbb7d61

**Comment by pasynkov** [comment]
+1

**Comment by substack** [comment]
Should be fixed in 3.7.5.

**Comment by youknowriad** [comment]
tks

**Comment by superbrothers** [comment]
Thank you for quick fix!
