### ISSUE TITLE
npm ERR! notarget No compatible version found: JSONStream@'>=1.0.3 <2.0.0'

### ISSUE THREAD

**Issue by Drarok** [substack/module-deps#85]
Error as above when attempting to install watchify, which uses module-deps.

Latest appears to be 1.0.1: https://github.com/dominictarr/JSONStream/releases

**Comment by terinjokes** [comment]
This repo has already been fixed, we're currently fixing the other dependencies of watchify/browserify, see https://github.com/substack/node-browserify/issues/1249
